/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoveryPlaylistRouteImport } from './routes/discovery.playlist'
import { Route as DiscoveryLevelRouteImport } from './routes/discovery.level'
import { Route as DiscoveryGeneratingRouteImport } from './routes/discovery.generating'
import { Route as ApiRecommendationsRouteImport } from './routes/api/recommendations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryPlaylistRoute = DiscoveryPlaylistRouteImport.update({
  id: '/discovery/playlist',
  path: '/discovery/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryLevelRoute = DiscoveryLevelRouteImport.update({
  id: '/discovery/level',
  path: '/discovery/level',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryGeneratingRoute = DiscoveryGeneratingRouteImport.update({
  id: '/discovery/generating',
  path: '/discovery/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsRoute = ApiRecommendationsRouteImport.update({
  id: '/api/recommendations',
  path: '/api/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/discovery/generating': typeof DiscoveryGeneratingRoute
  '/discovery/level': typeof DiscoveryLevelRoute
  '/discovery/playlist': typeof DiscoveryPlaylistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/discovery/generating': typeof DiscoveryGeneratingRoute
  '/discovery/level': typeof DiscoveryLevelRoute
  '/discovery/playlist': typeof DiscoveryPlaylistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/discovery/generating': typeof DiscoveryGeneratingRoute
  '/discovery/level': typeof DiscoveryLevelRoute
  '/discovery/playlist': typeof DiscoveryPlaylistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/recommendations'
    | '/discovery/generating'
    | '/discovery/level'
    | '/discovery/playlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/recommendations'
    | '/discovery/generating'
    | '/discovery/level'
    | '/discovery/playlist'
  id:
    | '__root__'
    | '/'
    | '/api/recommendations'
    | '/discovery/generating'
    | '/discovery/level'
    | '/discovery/playlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRecommendationsRoute: typeof ApiRecommendationsRoute
  DiscoveryGeneratingRoute: typeof DiscoveryGeneratingRoute
  DiscoveryLevelRoute: typeof DiscoveryLevelRoute
  DiscoveryPlaylistRoute: typeof DiscoveryPlaylistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/playlist': {
      id: '/discovery/playlist'
      path: '/discovery/playlist'
      fullPath: '/discovery/playlist'
      preLoaderRoute: typeof DiscoveryPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/level': {
      id: '/discovery/level'
      path: '/discovery/level'
      fullPath: '/discovery/level'
      preLoaderRoute: typeof DiscoveryLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/generating': {
      id: '/discovery/generating'
      path: '/discovery/generating'
      fullPath: '/discovery/generating'
      preLoaderRoute: typeof DiscoveryGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations': {
      id: '/api/recommendations'
      path: '/api/recommendations'
      fullPath: '/api/recommendations'
      preLoaderRoute: typeof ApiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRecommendationsRoute: ApiRecommendationsRoute,
  DiscoveryGeneratingRoute: DiscoveryGeneratingRoute,
  DiscoveryLevelRoute: DiscoveryLevelRoute,
  DiscoveryPlaylistRoute: DiscoveryPlaylistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
